# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/MagscopeWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1728, 994)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font-size: 18pt; font: Arial;")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 850, 691, 111))
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setStyleSheet("font-size: 18pt; font: Arial;")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.VideoFeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.VideoFeedLabel.setGeometry(QtCore.QRect(10, 5, 1330, 801))
        self.VideoFeedLabel.setMouseTracking(True)
        self.VideoFeedLabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.VideoFeedLabel.setText("")
        self.VideoFeedLabel.setObjectName("VideoFeedLabel")
        self.frameslider = QtWidgets.QProgressBar(self.centralwidget)
        self.frameslider.setGeometry(QtCore.QRect(10, 812, 1321, 31))
        self.frameslider.setStyleSheet("    QProgressBar {\n"
"        border: 2px solid rgba(33, 37, 43, 180);\n"
"        border-radius: 5px;\n"
"        text-align: center;\n"
"        background-color: rgba(33, 37, 43, 180);\n"
"        color: black;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        background-color: #FFD700;\n"
"    }")
        self.frameslider.setMinimum(0)
        self.frameslider.setMaximum(100)
        self.frameslider.setProperty("value", 0)
        self.frameslider.setObjectName("frameslider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(374, 850))
        self.dockWidget.setStyleSheet("")
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("font-size: 18pt; font: Arial;")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tracking_tab = QtWidgets.QWidget()
        self.tracking_tab.setObjectName("tracking_tab")
        self.choosevideobutton = QtWidgets.QPushButton(self.tracking_tab)
        self.choosevideobutton.setGeometry(QtCore.QRect(30, 0, 271, 31))
        self.choosevideobutton.setStyleSheet("     QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"            \n"
"            \n"
"            }")
        self.choosevideobutton.setObjectName("choosevideobutton")
        self.trackbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.trackbutton.setGeometry(QtCore.QRect(20, 40, 151, 91))
        self.trackbutton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.trackbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(0, 255, 0);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.trackbutton.setCheckable(True)
        self.trackbutton.setObjectName("trackbutton")
        self.framelabel = QtWidgets.QLabel(self.tracking_tab)
        self.framelabel.setGeometry(QtCore.QRect(190, 40, 121, 21))
        self.framelabel.setMaximumSize(QtCore.QSize(300, 25))
        self.framelabel.setObjectName("framelabel")
        self.pausebutton = QtWidgets.QPushButton(self.tracking_tab)
        self.pausebutton.setGeometry(QtCore.QRect(190, 70, 141, 30))
        self.pausebutton.setMaximumSize(QtCore.QSize(300, 30))
        self.pausebutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(150, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(150, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 150);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                font: bold 12px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(255, 0, 0);\n"
"                padding-left: 2px;\n"
"                padding-top: 2px;\n"
"            }")
        self.pausebutton.setCheckable(True)
        self.pausebutton.setObjectName("pausebutton")
        self.leftbutton = QtWidgets.QToolButton(self.tracking_tab)
        self.leftbutton.setGeometry(QtCore.QRect(200, 110, 51, 31))
        self.leftbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:pressed {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.leftbutton.setAutoRepeat(True)
        self.leftbutton.setAutoRepeatInterval(1)
        self.leftbutton.setArrowType(QtCore.Qt.LeftArrow)
        self.leftbutton.setObjectName("leftbutton")
        self.rightbutton = QtWidgets.QToolButton(self.tracking_tab)
        self.rightbutton.setGeometry(QtCore.QRect(270, 110, 50, 31))
        self.rightbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:pressed {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.rightbutton.setAutoRepeat(True)
        self.rightbutton.setAutoRepeatInterval(1)
        self.rightbutton.setArrowType(QtCore.Qt.RightArrow)
        self.rightbutton.setObjectName("rightbutton")
        self.maskbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.maskbutton.setGeometry(QtCore.QRect(20, 140, 81, 41))
        self.maskbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-style: inset;\n"
"              border-color: rgb(0, 255, 0);\n"
"            }")
        self.maskbutton.setCheckable(True)
        self.maskbutton.setChecked(False)
        self.maskbutton.setObjectName("maskbutton")
        self.maskinvert_checkBox = QtWidgets.QCheckBox(self.tracking_tab)
        self.maskinvert_checkBox.setGeometry(QtCore.QRect(110, 145, 191, 31))
        self.maskinvert_checkBox.setChecked(True)
        self.maskinvert_checkBox.setObjectName("maskinvert_checkBox")
        self.CroppedVideoFeedLabel = QtWidgets.QLabel(self.tracking_tab)
        self.CroppedVideoFeedLabel.setGeometry(QtCore.QRect(15, 555, 310, 310))
        self.CroppedVideoFeedLabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.CroppedVideoFeedLabel.setText("")
        self.CroppedVideoFeedLabel.setObjectName("CroppedVideoFeedLabel")
        self.resetdefaultbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.resetdefaultbutton.setGeometry(QtCore.QRect(105, 870, 121, 25))
        self.resetdefaultbutton.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.resetdefaultbutton.setFont(font)
        self.resetdefaultbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(100, 100, 100);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(100, 100, 100);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(200, 200, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(200, 200, 200);\n"
"         \n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.resetdefaultbutton.setObjectName("resetdefaultbutton")
        self.robotparamsframe = QtWidgets.QFrame(self.tracking_tab)
        self.robotparamsframe.setGeometry(QtCore.QRect(70, 450, 211, 101))
        self.robotparamsframe.setStyleSheet(" color: rgb(0, 0, 0);\n"
" background-color: rgb(255, 255, 255);\n"
"")
        self.robotparamsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.robotparamsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robotparamsframe.setObjectName("robotparamsframe")
        self.robotsizelabel = QtWidgets.QLabel(self.robotparamsframe)
        self.robotsizelabel.setGeometry(QtCore.QRect(0, 0, 201, 20))
        self.robotsizelabel.setMaximumSize(QtCore.QSize(300, 50))
        self.robotsizelabel.setObjectName("robotsizelabel")
        self.robotvelocitylabel = QtWidgets.QLabel(self.robotparamsframe)
        self.robotvelocitylabel.setGeometry(QtCore.QRect(0, 35, 191, 21))
        self.robotvelocitylabel.setMaximumSize(QtCore.QSize(300, 50))
        self.robotvelocitylabel.setObjectName("robotvelocitylabel")
        self.robotblurlabel = QtWidgets.QLabel(self.robotparamsframe)
        self.robotblurlabel.setGeometry(QtCore.QRect(0, 70, 201, 17))
        self.robotblurlabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.robotblurlabel.setObjectName("robotblurlabel")
        self.sizelcdnum = QtWidgets.QLCDNumber(self.robotparamsframe)
        self.sizelcdnum.setGeometry(QtCore.QRect(40, 0, 61, 30))
        self.sizelcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(255,0,255);")
        self.sizelcdnum.setLineWidth(0)
        self.sizelcdnum.setMidLineWidth(0)
        self.sizelcdnum.setSmallDecimalPoint(False)
        self.sizelcdnum.setDigitCount(3)
        self.sizelcdnum.setMode(QtWidgets.QLCDNumber.Dec)
        self.sizelcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.sizelcdnum.setProperty("value", 20.0)
        self.sizelcdnum.setObjectName("sizelcdnum")
        self.vellcdnum = QtWidgets.QLCDNumber(self.robotparamsframe)
        self.vellcdnum.setGeometry(QtCore.QRect(70, 35, 71, 30))
        self.vellcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(255,0,255);")
        self.vellcdnum.setLineWidth(0)
        self.vellcdnum.setMidLineWidth(0)
        self.vellcdnum.setSmallDecimalPoint(True)
        self.vellcdnum.setDigitCount(4)
        self.vellcdnum.setMode(QtWidgets.QLCDNumber.Dec)
        self.vellcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.vellcdnum.setProperty("value", 17.1)
        self.vellcdnum.setObjectName("vellcdnum")
        self.blurlcdnum = QtWidgets.QLCDNumber(self.robotparamsframe)
        self.blurlcdnum.setGeometry(QtCore.QRect(50, 70, 61, 30))
        self.blurlcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(255,0,255);")
        self.blurlcdnum.setLineWidth(0)
        self.blurlcdnum.setMidLineWidth(0)
        self.blurlcdnum.setSmallDecimalPoint(True)
        self.blurlcdnum.setDigitCount(3)
        self.blurlcdnum.setMode(QtWidgets.QLCDNumber.Dec)
        self.blurlcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.blurlcdnum.setProperty("value", 137.0)
        self.blurlcdnum.setObjectName("blurlcdnum")
        self.trackerparamsframe = QtWidgets.QFrame(self.tracking_tab)
        self.trackerparamsframe.setGeometry(QtCore.QRect(10, 235, 331, 211))
        self.trackerparamsframe.setStyleSheet("")
        self.trackerparamsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackerparamsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackerparamsframe.setObjectName("trackerparamsframe")
        self.maskthreshbox = QtWidgets.QSpinBox(self.trackerparamsframe)
        self.maskthreshbox.setGeometry(QtCore.QRect(160, 10, 111, 35))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.maskthreshbox.setFont(font)
        self.maskthreshbox.setStyleSheet("")
        self.maskthreshbox.setMaximum(255)
        self.maskthreshbox.setProperty("value", 128)
        self.maskthreshbox.setObjectName("maskthreshbox")
        self.maskthreshlabel = QtWidgets.QLabel(self.trackerparamsframe)
        self.maskthreshlabel.setGeometry(QtCore.QRect(40, 10, 121, 25))
        self.maskthreshlabel.setMaximumSize(QtCore.QSize(150, 25))
        self.maskthreshlabel.setObjectName("maskthreshlabel")
        self.maskdilationbox = QtWidgets.QSpinBox(self.trackerparamsframe)
        self.maskdilationbox.setGeometry(QtCore.QRect(160, 50, 111, 35))
        self.maskdilationbox.setMaximum(40)
        self.maskdilationbox.setObjectName("maskdilationbox")
        self.maskdilationlabel = QtWidgets.QLabel(self.trackerparamsframe)
        self.maskdilationlabel.setGeometry(QtCore.QRect(40, 50, 121, 25))
        self.maskdilationlabel.setMaximumSize(QtCore.QSize(150, 25))
        self.maskdilationlabel.setObjectName("maskdilationlabel")
        self.croplengthbox = QtWidgets.QSpinBox(self.trackerparamsframe)
        self.croplengthbox.setGeometry(QtCore.QRect(160, 90, 111, 35))
        self.croplengthbox.setMinimum(5)
        self.croplengthbox.setMaximum(300)
        self.croplengthbox.setProperty("value", 40)
        self.croplengthbox.setDisplayIntegerBase(10)
        self.croplengthbox.setObjectName("croplengthbox")
        self.croplengthlabel = QtWidgets.QLabel(self.trackerparamsframe)
        self.croplengthlabel.setGeometry(QtCore.QRect(40, 90, 121, 25))
        self.croplengthlabel.setMaximumSize(QtCore.QSize(150, 25))
        self.croplengthlabel.setObjectName("croplengthlabel")
        self.exposurebox = QtWidgets.QSpinBox(self.trackerparamsframe)
        self.exposurebox.setGeometry(QtCore.QRect(160, 130, 111, 35))
        self.exposurebox.setMinimum(100)
        self.exposurebox.setMaximum(10000)
        self.exposurebox.setProperty("value", 5000)
        self.exposurebox.setDisplayIntegerBase(10)
        self.exposurebox.setObjectName("exposurebox")
        self.exposurelabel = QtWidgets.QLabel(self.trackerparamsframe)
        self.exposurelabel.setGeometry(QtCore.QRect(40, 130, 83, 25))
        self.exposurelabel.setMaximumSize(QtCore.QSize(150, 25))
        self.exposurelabel.setObjectName("exposurelabel")
        self.objectivebox = QtWidgets.QSpinBox(self.trackerparamsframe)
        self.objectivebox.setGeometry(QtCore.QRect(160, 170, 111, 35))
        self.objectivebox.setMinimum(1)
        self.objectivebox.setMaximum(50)
        self.objectivebox.setSingleStep(5)
        self.objectivebox.setProperty("value", 10)
        self.objectivebox.setDisplayIntegerBase(10)
        self.objectivebox.setObjectName("objectivebox")
        self.objectivelabel = QtWidgets.QLabel(self.trackerparamsframe)
        self.objectivelabel.setGeometry(QtCore.QRect(40, 170, 83, 25))
        self.objectivelabel.setMaximumSize(QtCore.QSize(150, 25))
        self.objectivelabel.setObjectName("objectivelabel")
        self.savedatabutton = QtWidgets.QPushButton(self.tracking_tab)
        self.savedatabutton.setGeometry(QtCore.QRect(30, 185, 131, 41))
        self.savedatabutton.setStyleSheet("QPushButton {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 255, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 255, 100);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(255, 255, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: red;\n"
"                border: 2px solid red;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.savedatabutton.setCheckable(True)
        self.savedatabutton.setObjectName("savedatabutton")
        self.recordbutton = QtWidgets.QPushButton(self.tracking_tab)
        self.recordbutton.setGeometry(QtCore.QRect(180, 185, 131, 41))
        self.recordbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.recordbutton.setCheckable(True)
        self.recordbutton.setObjectName("recordbutton")
        self.tabWidget.addTab(self.tracking_tab, "")
        self.control_tab = QtWidgets.QWidget()
        self.control_tab.setObjectName("control_tab")
        self.magneticfieldsimlabel = QtWidgets.QLabel(self.control_tab)
        self.magneticfieldsimlabel.setGeometry(QtCore.QRect(15, 555, 310, 310))
        self.magneticfieldsimlabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.magneticfieldsimlabel.setText("")
        self.magneticfieldsimlabel.setObjectName("magneticfieldsimlabel")
        self.simulationbutton = QtWidgets.QPushButton(self.control_tab)
        self.simulationbutton.setGeometry(QtCore.QRect(75, 870, 171, 25))
        self.simulationbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 255, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 100, 0);\n"
"                min-width: 1em;\n"
"                padding: 2px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 100, 0);\n"
"                border-style: inset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.simulationbutton.setCheckable(True)
        self.simulationbutton.setObjectName("simulationbutton")
        self.bxlabel = QtWidgets.QLabel(self.control_tab)
        self.bxlabel.setGeometry(QtCore.QRect(220, 195, 121, 41))
        self.bxlabel.setObjectName("bxlabel")
        self.bylabel = QtWidgets.QLabel(self.control_tab)
        self.bylabel.setGeometry(QtCore.QRect(220, 240, 121, 41))
        self.bylabel.setObjectName("bylabel")
        self.bzlabel = QtWidgets.QLabel(self.control_tab)
        self.bzlabel.setGeometry(QtCore.QRect(220, 285, 121, 41))
        self.bzlabel.setObjectName("bzlabel")
        self.leftfieldbutton = QtWidgets.QToolButton(self.control_tab)
        self.leftfieldbutton.setGeometry(QtCore.QRect(10, 270, 51, 31))
        self.leftfieldbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.leftfieldbutton.setCheckable(True)
        self.leftfieldbutton.setAutoRepeat(False)
        self.leftfieldbutton.setAutoRepeatInterval(1)
        self.leftfieldbutton.setArrowType(QtCore.Qt.LeftArrow)
        self.leftfieldbutton.setObjectName("leftfieldbutton")
        self.rightfieldbutton = QtWidgets.QToolButton(self.control_tab)
        self.rightfieldbutton.setGeometry(QtCore.QRect(130, 270, 51, 31))
        self.rightfieldbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.rightfieldbutton.setCheckable(True)
        self.rightfieldbutton.setAutoRepeat(False)
        self.rightfieldbutton.setAutoRepeatInterval(1)
        self.rightfieldbutton.setArrowType(QtCore.Qt.RightArrow)
        self.rightfieldbutton.setObjectName("rightfieldbutton")
        self.downfieldbutton = QtWidgets.QToolButton(self.control_tab)
        self.downfieldbutton.setGeometry(QtCore.QRect(70, 290, 51, 31))
        self.downfieldbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.downfieldbutton.setCheckable(True)
        self.downfieldbutton.setAutoRepeat(False)
        self.downfieldbutton.setAutoRepeatInterval(1)
        self.downfieldbutton.setArrowType(QtCore.Qt.DownArrow)
        self.downfieldbutton.setObjectName("downfieldbutton")
        self.upfieldbutton = QtWidgets.QToolButton(self.control_tab)
        self.upfieldbutton.setGeometry(QtCore.QRect(70, 250, 51, 31))
        self.upfieldbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"           \n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.upfieldbutton.setCheckable(True)
        self.upfieldbutton.setChecked(False)
        self.upfieldbutton.setAutoRepeat(False)
        self.upfieldbutton.setAutoRepeatInterval(1)
        self.upfieldbutton.setArrowType(QtCore.Qt.UpArrow)
        self.upfieldbutton.setObjectName("upfieldbutton")
        self.quickfieldlabel = QtWidgets.QLabel(self.control_tab)
        self.quickfieldlabel.setGeometry(QtCore.QRect(50, 190, 101, 21))
        self.quickfieldlabel.setObjectName("quickfieldlabel")
        self.controlparamsframe = QtWidgets.QFrame(self.control_tab)
        self.controlparamsframe.setGeometry(QtCore.QRect(10, 330, 331, 221))
        self.controlparamsframe.setStyleSheet("")
        self.controlparamsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlparamsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlparamsframe.setObjectName("controlparamsframe")
        self.rollingfrequencylabel = QtWidgets.QLabel(self.controlparamsframe)
        self.rollingfrequencylabel.setGeometry(QtCore.QRect(230, 200, 81, 21))
        self.rollingfrequencylabel.setObjectName("rollingfrequencylabel")
        self.RRTtreesizebox = QtWidgets.QSpinBox(self.controlparamsframe)
        self.RRTtreesizebox.setGeometry(QtCore.QRect(120, 40, 71, 35))
        self.RRTtreesizebox.setMinimum(1)
        self.RRTtreesizebox.setMaximum(100)
        self.RRTtreesizebox.setProperty("value", 25)
        self.RRTtreesizebox.setObjectName("RRTtreesizebox")
        self.psidial = QtWidgets.QDial(self.controlparamsframe)
        self.psidial.setGeometry(QtCore.QRect(0, 90, 91, 101))
        self.psidial.setStyleSheet("QDial\n"
"    {\n"
"        background-color:QLinearGradient( \n"
"            x1: 0.177, y1: 0.004, x2: 0.831, y2: 0.911, \n"
"            stop: 0 white, \n"
"            stop: 0.061 white, \n"
"            stop: 0.066 lightgray, \n"
"            stop: 0.5 #242424, \n"
"            stop: 0.505 #000000,\n"
"            stop: 0.827 #040404,\n"
"            stop: 0.966 #292929,\n"
"            stop: 0.983 #2e2e2e\n"
"        );\n"
"    }")
        self.psidial.setMinimum(1)
        self.psidial.setMaximum(90)
        self.psidial.setSingleStep(5)
        self.psidial.setProperty("value", 90)
        self.psidial.setNotchTarget(10.0)
        self.psidial.setNotchesVisible(True)
        self.psidial.setObjectName("psidial")
        self.memorylabel = QtWidgets.QLabel(self.controlparamsframe)
        self.memorylabel.setGeometry(QtCore.QRect(5, 10, 71, 21))
        self.memorylabel.setObjectName("memorylabel")
        self.RRTtreesizelabel = QtWidgets.QLabel(self.controlparamsframe)
        self.RRTtreesizelabel.setGeometry(QtCore.QRect(115, 10, 81, 21))
        self.RRTtreesizelabel.setObjectName("RRTtreesizelabel")
        self.arrivalthreshlabel = QtWidgets.QLabel(self.controlparamsframe)
        self.arrivalthreshlabel.setGeometry(QtCore.QRect(210, 10, 111, 21))
        self.arrivalthreshlabel.setObjectName("arrivalthreshlabel")
        self.gammalabel = QtWidgets.QLabel(self.controlparamsframe)
        self.gammalabel.setGeometry(QtCore.QRect(100, 200, 101, 20))
        self.gammalabel.setObjectName("gammalabel")
        self.psilabel = QtWidgets.QLabel(self.controlparamsframe)
        self.psilabel.setGeometry(QtCore.QRect(10, 200, 71, 21))
        self.psilabel.setObjectName("psilabel")
        self.magneticfrequencydial = QtWidgets.QDial(self.controlparamsframe)
        self.magneticfrequencydial.setGeometry(QtCore.QRect(220, 90, 91, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.magneticfrequencydial.setFont(font)
        self.magneticfrequencydial.setStyleSheet("QDial {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #1a5276, stop:0.3 #2980b9, stop:0.7 #3498db, stop:1 #1a5276);\n"
"    border: 2px solid #1a5276;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDial::handle {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #f39c12, stop:0.3 #f1c40f, stop:0.7 #f39c12, stop:1 #f1c40f);\n"
"    border: 2px solid #e67e22;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -5px;\n"
"}\n"
"")
        self.magneticfrequencydial.setMaximum(40)
        self.magneticfrequencydial.setSingleStep(1)
        self.magneticfrequencydial.setPageStep(1)
        self.magneticfrequencydial.setProperty("value", 10)
        self.magneticfrequencydial.setOrientation(QtCore.Qt.Horizontal)
        self.magneticfrequencydial.setWrapping(False)
        self.magneticfrequencydial.setNotchTarget(10.0)
        self.magneticfrequencydial.setNotchesVisible(True)
        self.magneticfrequencydial.setObjectName("magneticfrequencydial")
        self.gammadial = QtWidgets.QDial(self.controlparamsframe)
        self.gammadial.setGeometry(QtCore.QRect(110, 90, 91, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.gammadial.setFont(font)
        self.gammadial.setStyleSheet("QDial {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #1a5276, stop:0.3 #2980b9, stop:0.7 #3498db, stop:1 #1a5276);\n"
"    border: 2px solid #1a5276;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDial::handle {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #f39c12, stop:0.3 #f1c40f, stop:0.7 #f39c12, stop:1 #f1c40f);\n"
"    border: 2px solid #e67e22;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -5px;\n"
"}\n"
"")
        self.gammadial.setMaximum(180)
        self.gammadial.setSingleStep(5)
        self.gammadial.setPageStep(10)
        self.gammadial.setProperty("value", 90)
        self.gammadial.setOrientation(QtCore.Qt.Horizontal)
        self.gammadial.setWrapping(False)
        self.gammadial.setNotchTarget(10.0)
        self.gammadial.setNotchesVisible(True)
        self.gammadial.setObjectName("gammadial")
        self.arrivalthreshbox = QtWidgets.QSpinBox(self.controlparamsframe)
        self.arrivalthreshbox.setGeometry(QtCore.QRect(230, 40, 71, 35))
        self.arrivalthreshbox.setMinimum(1)
        self.arrivalthreshbox.setMaximum(100)
        self.arrivalthreshbox.setProperty("value", 20)
        self.arrivalthreshbox.setObjectName("arrivalthreshbox")
        self.memorybox = QtWidgets.QSpinBox(self.controlparamsframe)
        self.memorybox.setGeometry(QtCore.QRect(5, 40, 71, 35))
        self.memorybox.setMinimum(1)
        self.memorybox.setMaximum(100)
        self.memorybox.setProperty("value", 15)
        self.memorybox.setObjectName("memorybox")
        self.frame = QtWidgets.QFrame(self.control_tab)
        self.frame.setGeometry(QtCore.QRect(10, 0, 331, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.led = QtWidgets.QLabel(self.frame)
        self.led.setGeometry(QtCore.QRect(270, 140, 30, 30))
        self.led.setStyleSheet("\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 12px;\n"
"                border-color: rgb(255, 0, 0);\n"
"         \n"
"                padding: 6px;")
        self.led.setText("")
        self.led.setObjectName("led")
        self.swimradio = QtWidgets.QRadioButton(self.frame)
        self.swimradio.setGeometry(QtCore.QRect(120, 70, 71, 20))
        self.swimradio.setObjectName("swimradio")
        self.applyacousticbutton = QtWidgets.QPushButton(self.frame)
        self.applyacousticbutton.setGeometry(QtCore.QRect(185, 135, 81, 41))
        self.applyacousticbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(0, 0, 0);\n"
"                border-style: inset;\n"
"            }\n"
"\n"
"         QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(200, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"}")
        self.applyacousticbutton.setCheckable(True)
        self.applyacousticbutton.setObjectName("applyacousticbutton")
        self.rollradio = QtWidgets.QRadioButton(self.frame)
        self.rollradio.setGeometry(QtCore.QRect(20, 70, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.rollradio.setFont(font)
        self.rollradio.setChecked(True)
        self.rollradio.setObjectName("rollradio")
        self.joystickbutton = QtWidgets.QPushButton(self.frame)
        self.joystickbutton.setGeometry(QtCore.QRect(150, 10, 131, 51))
        self.joystickbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(0, 255, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 255, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(0, 200, 200);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 200, 200);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"              padding-left: 5px;\n"
"                padding-top: 5px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.joystickbutton.setCheckable(True)
        self.joystickbutton.setObjectName("joystickbutton")
        self.controlbutton = QtWidgets.QPushButton(self.frame)
        self.controlbutton.setGeometry(QtCore.QRect(20, 10, 121, 51))
        self.controlbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(0, 255, 0);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.controlbutton.setCheckable(True)
        self.controlbutton.setObjectName("controlbutton")
        self.orientradio = QtWidgets.QRadioButton(self.frame)
        self.orientradio.setGeometry(QtCore.QRect(220, 70, 71, 20))
        self.orientradio.setObjectName("orientradio")
        self.acousticfreq_spinBox = QtWidgets.QSpinBox(self.frame)
        self.acousticfreq_spinBox.setGeometry(QtCore.QRect(5, 135, 171, 41))
        self.acousticfreq_spinBox.setMaximum(3000000)
        self.acousticfreq_spinBox.setObjectName("acousticfreq_spinBox")
        self.acousticfreqlabel = QtWidgets.QLabel(self.frame)
        self.acousticfreqlabel.setGeometry(QtCore.QRect(55, 105, 181, 21))
        self.acousticfreqlabel.setObjectName("acousticfreqlabel")
        self.plusZbutton = QtWidgets.QToolButton(self.control_tab)
        self.plusZbutton.setGeometry(QtCore.QRect(130, 220, 51, 31))
        self.plusZbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.plusZbutton.setCheckable(True)
        self.plusZbutton.setAutoRepeat(False)
        self.plusZbutton.setAutoRepeatInterval(1)
        self.plusZbutton.setArrowType(QtCore.Qt.NoArrow)
        self.plusZbutton.setObjectName("plusZbutton")
        self.minusZbutton = QtWidgets.QToolButton(self.control_tab)
        self.minusZbutton.setGeometry(QtCore.QRect(10, 220, 51, 31))
        self.minusZbutton.setStyleSheet("QToolButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: px;\n"
"                border-radius: 10px;\n"
"                border: 2px solid rgb(0, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QToolButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border: 2px solid rgb(0, 255, 0);\n"
"            }\n"
"            QToolButton:checked {\n"
"                background-color: rgb(100, 100, 100);\n"
"                border: 2px solid rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.minusZbutton.setCheckable(True)
        self.minusZbutton.setAutoRepeat(False)
        self.minusZbutton.setAutoRepeatInterval(1)
        self.minusZbutton.setArrowType(QtCore.Qt.NoArrow)
        self.minusZbutton.setObjectName("minusZbutton")
        self.bxlcdnum = QtWidgets.QLCDNumber(self.control_tab)
        self.bxlcdnum.setGeometry(QtCore.QRect(250, 200, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.bxlcdnum.setFont(font)
        self.bxlcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(255,0,0);\n"
"")
        self.bxlcdnum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bxlcdnum.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bxlcdnum.setLineWidth(0)
        self.bxlcdnum.setMidLineWidth(1)
        self.bxlcdnum.setSmallDecimalPoint(False)
        self.bxlcdnum.setDigitCount(3)
        self.bxlcdnum.setMode(QtWidgets.QLCDNumber.Dec)
        self.bxlcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bxlcdnum.setProperty("value", 5.4)
        self.bxlcdnum.setObjectName("bxlcdnum")
        self.bylcdnum = QtWidgets.QLCDNumber(self.control_tab)
        self.bylcdnum.setGeometry(QtCore.QRect(250, 245, 61, 31))
        self.bylcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(0,255,0);")
        self.bylcdnum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bylcdnum.setLineWidth(2)
        self.bylcdnum.setMidLineWidth(1)
        self.bylcdnum.setDigitCount(3)
        self.bylcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bylcdnum.setProperty("value", 5.4)
        self.bylcdnum.setObjectName("bylcdnum")
        self.bzlcdnum = QtWidgets.QLCDNumber(self.control_tab)
        self.bzlcdnum.setGeometry(QtCore.QRect(250, 290, 61, 31))
        self.bzlcdnum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bzlcdnum.setAutoFillBackground(False)
        self.bzlcdnum.setStyleSheet("background-color: rgb(255,255,255); \n"
"color: rgb(0,0,255);")
        self.bzlcdnum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bzlcdnum.setLineWidth(2)
        self.bzlcdnum.setMidLineWidth(1)
        self.bzlcdnum.setDigitCount(3)
        self.bzlcdnum.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.bzlcdnum.setProperty("value", 5.4)
        self.bzlcdnum.setObjectName("bzlcdnum")
        self.tabWidget.addTab(self.control_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actiondock = QtWidgets.QAction(MainWindow)
        self.actiondock.setMenuRole(QtWidgets.QAction.NoRole)
        self.actiondock.setObjectName("actiondock")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frameslider.setFormat(_translate("MainWindow", "Frame %v"))
        self.choosevideobutton.setText(_translate("MainWindow", "Choose Video"))
        self.trackbutton.setText(_translate("MainWindow", "Track"))
        self.framelabel.setText(_translate("MainWindow", "Frame: "))
        self.pausebutton.setText(_translate("MainWindow", "Pause"))
        self.leftbutton.setText(_translate("MainWindow", "..."))
        self.rightbutton.setText(_translate("MainWindow", "..."))
        self.maskbutton.setText(_translate("MainWindow", "Mask"))
        self.maskinvert_checkBox.setText(_translate("MainWindow", "Invert Mask: True"))
        self.resetdefaultbutton.setText(_translate("MainWindow", "Defaults"))
        self.robotsizelabel.setText(_translate("MainWindow", "Size:                  px"))
        self.robotvelocitylabel.setText(_translate("MainWindow", "Velocity:                    px/s"))
        self.robotblurlabel.setText(_translate("MainWindow", "Blur:                      units"))
        self.maskthreshlabel.setText(_translate("MainWindow", "Mask Thresh"))
        self.maskdilationlabel.setText(_translate("MainWindow", "Mask Dilation"))
        self.croplengthlabel.setText(_translate("MainWindow", "Crop Length"))
        self.exposurelabel.setText(_translate("MainWindow", "Exposure"))
        self.objectivelabel.setText(_translate("MainWindow", "Objective"))
        self.savedatabutton.setText(_translate("MainWindow", "Save Data"))
        self.recordbutton.setText(_translate("MainWindow", "Record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tracking_tab), _translate("MainWindow", "Tracking"))
        self.simulationbutton.setText(_translate("MainWindow", "Simulation On"))
        self.bxlabel.setText(_translate("MainWindow", "Bx:                 mT"))
        self.bylabel.setText(_translate("MainWindow", "By:                 mT"))
        self.bzlabel.setText(_translate("MainWindow", "Bz:                 mT"))
        self.leftfieldbutton.setText(_translate("MainWindow", "..."))
        self.rightfieldbutton.setText(_translate("MainWindow", "..."))
        self.downfieldbutton.setText(_translate("MainWindow", "..."))
        self.upfieldbutton.setText(_translate("MainWindow", "..."))
        self.quickfieldlabel.setText(_translate("MainWindow", "Quick Field"))
        self.rollingfrequencylabel.setText(_translate("MainWindow", "Freq: 10"))
        self.memorylabel.setText(_translate("MainWindow", "Memory"))
        self.RRTtreesizelabel.setText(_translate("MainWindow", "Tree Size"))
        self.arrivalthreshlabel.setText(_translate("MainWindow", "Arrive Thresh"))
        self.gammalabel.setText(_translate("MainWindow", "Gamma: 90"))
        self.psilabel.setText(_translate("MainWindow", "Psi: 90"))
        self.swimradio.setText(_translate("MainWindow", "Swim"))
        self.applyacousticbutton.setText(_translate("MainWindow", "Apply"))
        self.rollradio.setText(_translate("MainWindow", "Roll"))
        self.joystickbutton.setText(_translate("MainWindow", "Joystick"))
        self.controlbutton.setText(_translate("MainWindow", "Control"))
        self.orientradio.setText(_translate("MainWindow", "Orient"))
        self.acousticfreqlabel.setText(_translate("MainWindow", "Acoustic Frequency"))
        self.plusZbutton.setText(_translate("MainWindow", "+Z"))
        self.minusZbutton.setText(_translate("MainWindow", "-Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), _translate("MainWindow", "Control"))
        self.actiondock.setText(_translate("MainWindow", "dock"))
